spring:
  datasource:
    password: 658
    url: jdbc:postgresql://localhost:5432/shalyapinLibrary
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect:
          org:
            hibernate:
              dialect:
  mvc:
    path match:
      matching-strategy: ant_path_matcher

server:
  port: 8080

keycloak:
  auth-server-url: http://localhost:8182
  realm: lib-realm
  resource: lib-client
  bearer-only: true
  public-client: true
  enabled: true