spring:
  profiles:
    active: local
  datasource:
    password: urPassword
    url: urUrl
    username: urUsername
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect:
          org:
            hibernate:
              dialect:
  mvc:
    path match:
      matching-strategy: ant_path_matcher

server:
  port: 8080

keycloak:
  auth-server-url: ururl
  realm: lib-realm
  resource: lib-client
  bearer-only: true
  public-client: true
  enabled: true