spring:
  datasource:
    password: "${DB_PASSWORD}"
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect:
          org:
            hibernate:
              dialect:
  mvc:
    path match:
      matching-strategy: ant_path_matcher

server:
  port: "${SERVER_PORT}"

keycloak:
  auth-server-url: "${KK_URL}"
  realm: "${KK_REALM}"
  resource: "${KK_REALM}"
  bearer-only: true
  public-client: true
  enabled: true