spring:
  datasource:
    password: "${DB_PASSWORD}"
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
  jpa:
    show-sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: "${SERVER_PORT}"

keycloak:
  auth-server-url: "${KK_URL}"
  realm: "${KK_REALM}"
  resource: "${KK_REALM}"
  bearer-only: true
  public-client: true
  enabled: true